<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UrlVersionHandler\Module'                        => __DIR__ . '/Module.php',
    'UrlVersionHandler\Controller\IndexController' => __DIR__ . '/src/UrlVersionHandler/Controller/IndexController.php',
    'UrlVersionHandlerTest\Framework\TestCase'        => __DIR__ . '/tests/UrlVersionHandler/Framework/TestCase.php',
    'UrlVersionHandlerTest\SampleTest'                => __DIR__ . '/tests/UrlVersionHandler/SampleTest.php',
);
